#!/usr/bin/env python3
"""Generate a human-browsable index of the HID dataset.

Reads all data/cves/*.yaml entries and writes:
  - data/cves/INDEX.md   (a sortable Markdown table)
  - data/cves/index.csv  (machine-readable flat export)

Run: python scripts/research-tools/build_index.py
CI runs this with --check to ensure the committed index is up to date.
"""

from __future__ import annotations

import csv
import io
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
CVE_DIR = REPO / "data" / "cves"
INDEX_MD = CVE_DIR / "INDEX.md"
INDEX_CSV = CVE_DIR / "index.csv"

CSV_FIELDS = [
    "id",
    "entry_type",
    "cve",
    "date",
    "title",
    "manufacturer",
    "transport",
    "attack_class",
    "attack_direction",
    "severity_base_score",
    "severity_base_severity",
    "evidence",
    "confidence",
]


def entries() -> list[dict]:
    out = []
    for p in sorted(CVE_DIR.glob("*.yaml")):
        if p.name.startswith("_"):
            continue
        out.append(yaml.safe_load(p.read_text()))
    return out


def flat(e: dict) -> dict:
    sev = e.get("severity") or {}
    return {
        "id": e.get("id", ""),
        "entry_type": e.get("entry_type", ""),
        "cve": e.get("cve") or "",
        "date": e.get("date", ""),
        "title": e.get("title", ""),
        "manufacturer": e.get("manufacturer") or "",
        "transport": "|".join(e.get("transport") or []),
        "attack_class": "|".join(e.get("attack_class") or []),
        "attack_direction": "|".join(e.get("attack_direction") or []),
        "severity_base_score": (
            sev.get("base_score") if sev.get("base_score") is not None else ""
        ),
        "severity_base_severity": sev.get("base_severity") or "",
        "evidence": e.get("evidence", ""),
        "confidence": e.get("confidence", ""),
    }


def render_csv(rows: list[dict]) -> str:
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=CSV_FIELDS, lineterminator="\n")
    w.writeheader()
    for r in rows:
        w.writerow(r)
    return buf.getvalue()


def render_md(es: list[dict]) -> str:
    rows = sorted(es, key=lambda e: (e.get("date", ""), e.get("id", "")), reverse=True)
    by_type: dict[str, int] = {}
    for e in es:
        by_type[e["entry_type"]] = by_type.get(e["entry_type"], 0) + 1

    lines = [
        "# HID Security Dataset Index",
        "",
        "> Auto-generated by `scripts/research-tools/build_index.py`. Do not edit by hand.",
        "> Source of truth is the per-entry YAML in this directory.",
        "",
        f"**{len(es)} entries** · last built from source YAML.",
        "",
        "## By entry type",
        "",
    ]
    for t, n in sorted(by_type.items()):
        lines.append(f"- `{t}`: {n}")
    lines += [
        "",
        "## All entries (newest first)",
        "",
        "| Date | ID | Type | CVE | Title | Transport | Classes | Sev | Evidence |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for e in rows:
        sev = e.get("severity") or {}
        sv = sev.get("base_severity") or ""
        score = sev.get("base_score")
        sev_disp = f"{sv} {score}".strip() if (sv or score is not None) else "—"
        lines.append(
            "| {date} | `{id}` | {etype} | {cve} | {title} | {tr} | {cls} | {sev} | {ev} |".format(
                date=e.get("date", ""),
                id=e.get("id", ""),
                etype=e.get("entry_type", ""),
                cve=e.get("cve") or "—",
                title=e.get("title", "").replace("|", "\\|"),
                tr=", ".join(e.get("transport") or []),
                cls=", ".join(e.get("attack_class") or []),
                sev=sev_disp,
                ev=e.get("evidence", ""),
            )
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    check = "--check" in sys.argv
    es = entries()
    md = render_md(es)
    rows = [flat(e) for e in es]
    csv_text = render_csv(rows)

    if check:
        stale = []
        if not INDEX_MD.exists() or INDEX_MD.read_text() != md:
            stale.append(str(INDEX_MD.relative_to(REPO)))
        if not INDEX_CSV.exists() or INDEX_CSV.read_text() != csv_text:
            stale.append(str(INDEX_CSV.relative_to(REPO)))
        if stale:
            print("Index out of date; run build_index.py and commit:")
            for s in stale:
                print(f"  - {s}")
            return 1
        print("OK: dataset index is up to date.")
        return 0

    INDEX_MD.write_text(md)
    INDEX_CSV.write_text(csv_text)
    print(
        f"Wrote {INDEX_MD.relative_to(REPO)} and {INDEX_CSV.relative_to(REPO)} ({len(es)} entries)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
